"""empty message

Revision ID: e731f1f48328
Revises: 06dd9ff51788
Create Date: 2020-03-30 06:33:57.626527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e731f1f48328'
down_revision = '06dd9ff51788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'date_created')
    # ### end Alembic commands ###
